# Generated by Django 5.2.7 on 2025-10-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('time_slot', models.TextField()),
                ('status', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBuildings',
            fields=[
                ('building_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_buildings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCollege',
            fields=[
                ('college_id', models.TextField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_college',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCourse',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCourseUsers',
            fields=[
                ('pk', models.CompositePrimaryKey('course_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, null=True)),
                ('is_bayanihan_leader', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_course_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDepartment',
            fields=[
                ('department_id', models.TextField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblExamdetails',
            fields=[
                ('examdetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50)),
                ('program_id', models.TextField()),
                ('exam_duration', models.DurationField(blank=True, null=True)),
                ('exam_start_time', models.DateTimeField(blank=True, null=True)),
                ('exam_end_time', models.DateTimeField(blank=True, null=True)),
                ('proctor_timein', models.DateTimeField(blank=True, null=True)),
                ('proctor_timeout', models.DateTimeField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, null=True)),
                ('academic_year', models.TextField(blank=True, null=True)),
                ('semester', models.TextField(blank=True, null=True)),
                ('exam_category', models.TextField(blank=True, null=True)),
                ('exam_period', models.TextField(blank=True, null=True)),
                ('exam_date', models.TextField(blank=True, null=True)),
                ('college_name', models.TextField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, null=True)),
                ('instructor_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_examdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblExamperiod',
            fields=[
                ('examperiod_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('academic_year', models.TextField()),
                ('exam_category', models.TextField()),
            ],
            options={
                'db_table': 'tbl_examperiod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblInbox',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('sender_uuid', models.UUIDField(blank=True, null=True)),
                ('receiver_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_inbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblModality',
            fields=[
                ('modality_id', models.AutoField(primary_key=True, serialize=False)),
                ('modality_type', models.TextField()),
                ('room_type', models.TextField()),
                ('modality_remarks', models.TextField(blank=True, null=True)),
                ('program_id', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, null=True)),
                ('possible_rooms', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_modality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNotifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=150)),
                ('receiver_name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProgram',
            fields=[
                ('program_id', models.TextField(primary_key=True, serialize=False)),
                ('program_name', models.TextField()),
            ],
            options={
                'db_table': 'tbl_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReplies',
            fields=[
                ('reply_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_replies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRoles',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField()),
            ],
            options={
                'db_table': 'tbl_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRooms',
            fields=[
                ('room_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=500)),
                ('room_type', models.CharField(max_length=500)),
                ('room_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblScheduleapproval',
            fields=[
                ('dean_user_id', models.IntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('file_url', models.TextField(blank=True, null=True)),
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('dean_college', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_scheduleapproval',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSectioncourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('number_of_students', models.IntegerField()),
                ('year_level', models.TextField()),
            ],
            options={
                'db_table': 'tbl_sectioncourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSystemNotification',
            fields=[
                ('notif_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sms_alert_sent', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_system_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTerm',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_name', models.TextField()),
            ],
            options={
                'db_table': 'tbl_term',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUserRoleHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_role_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('college_id', models.TextField(blank=True, null=True)),
                ('department_id', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_role_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('avatar_url', models.CharField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('user_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_users',
                'managed': False,
            },
        ),
    ]
